/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

#include "MP4.STSD.h"

using namespace MP4;
          
STSD::STSD( void )
{
    this->_type.append( "STSD" );
}

std::string STSD::description( void )
{
    std::ostringstream o;
    
    o << "MP4 Atom:           " << this->_type << "\n";
    
    return o.str();
}

void STSD::processData( MP4::BinaryStream * stream, size_t length ) //TDOD refactor this function add error checking
{
    (void)length;
    stream->ignore( 4 );
    uint32_t sampleEntries = stream->readBigEndianUnsignedInteger();
    if ( sampleEntries != 1 )
    {
        return;
    }

    stream->ignore( 4 );
    char type[ 5 ];
    stream->read( type, 4 );                //mp4a
    type[ 4 ] = '\0';

    stream->ignore( 8 );

    stream->readBigEndianUnsignedShort();   //sound version?
    stream->ignore( 18 );

    //todo depends on version
    //stream->ignore( 32 );

    stream->ignore( 4 );
    stream->read( type, 4 );                //esds
    type[ 4 ] = '\0';
    stream->ignore( 4 );

    stream->readUnsignedChar();             //ES tag 0x03
    uint8_t tagLen = 0;
    do
    {
      tagLen = stream->readUnsignedChar();
    }
    while ( tagLen == 0x80 );

    stream->ignore( 3 );                    //0x0

    stream->readUnsignedChar();             //DecoderConfig 0x04
    tagLen = 0;
    do
    {
      tagLen = stream->readUnsignedChar();
    }
    while ( tagLen == 0x80 );

    stream->readUnsignedChar();             //MPEG4 0x40
    stream->readUnsignedChar();             //Audio stream 0x15
    stream->ignore( 11 );

    stream->readUnsignedChar();             //DecoderSpecific 0x05
    tagLen = 0;
    do
    {
      tagLen = stream->readUnsignedChar();
    }
    while ( tagLen == 0x80 );

    uint16_t encFlags = stream->readBigEndianUnsignedShort();
    m_aot = ( encFlags & 0xF800 ) >> 11;
    m_sampleRate = ( encFlags & 0x780 ) >> 7;
    m_channelConfig = ( encFlags & 0x78 ) >> 3;

    stream->readUnsignedChar();             //0x06
    tagLen = 0;
    do
    {
      tagLen = stream->readUnsignedChar();
    }
    while ( tagLen == 0x80 );
    stream->ignore( 1 );
}
